#!/usr/bin/env sh
# don't crash out if there is an error
set +xe

setup()
{
    # it is possible that a PASSWORD environment variable was set by bootrino so we load bootrino environment variables
    set -o allexport
    [ -f /bootrino/envvars.sh ] && . /bootrino/envvars.sh
    set +o allexport
}
setup

set_password()
{
    # if bootrino user has not defined a password environment variable when launching then make a random one
    NEWPW=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c10`
    if ! [[ -z "${PASSWORD}" ]]; then
      NEWPW=${PASSWORD}
    fi
    echo "root:${NEWPW}" | chpasswd
    echo "Password for root user is ${NEWPW}"
    echo "Password for root user is ${NEWPW}" > /dev/console
    echo "Password for root user is ${NEWPW}" > /dev/tty0
    echo "Password can also be found in /root/rootpassword.txt"
    echo "${NEWPW}" > /root/rootpassword.txt
    chown root:root /root/rootpassword.txt
    chmod u=rx,g=,o= /root/rootpassword.txt
}
set_password
